### ISSUE TITLE
Sudo for softioc user?

### ISSUE THREAD

**Issue by sfeister** [NSLS-II/systemd-softioc#1]
Hi @huyong1979 and team, I've been running into some issues on Raspbian (Raspberry Pi's flavor of 32-bit Debian) where the systemd process won't start unless I use sudo, via "sudo manage-iocs start example1" -- but then when I do, the log shows that this aborts right away, with an error in the log saying that the softioc group/user does not have sudo access. Thoughts? I will post back with more details soon.

**Comment by huyong1979** [comment]
Hi, sorry for my late reponse. Somehow I did not receive any notifications about your message. The main purpose of the "generic" user account 'softioc': let "softioc" be the onwer of your IOC's directory as well as the owner of your IOC's process after the IOC is started (you can try: ps -ef | grep st.cmd). You should NOT (generally you CANNOT just as you reported) use "softioc" to start your softIOCs. Instead, type "exit" to exit from the account "softioc" to your own personal account, or open another termial, then type "sudo manage-iocs start example1".
