### ISSUE TITLE
install.sh does not try to install procServ if it is not present

### ISSUE THREAD

**Issue by mellguth2** [NSLS-II/systemd-softioc#2]
I ran the `install.sh` script (`sudo ./install.sh`) without any `procServ` binary on my system (Ubuntu 22.04 LTS)  and it just said "Done" when reaching the block that starts with the comment `#get, build and install procServ`. I then modified the script to comment out the block so the script would continue with the steps after that and it proceeded to fetch the procServ sources, build them and install procServ into the system, which was successful.

**Comment by leblancOUAL** [comment]
Yeah, I saw the same thing, but I'm not savvy enough to make those changes.  I also found that it won't look for procserv anywhere other than /usr/bin.  

Could you share your changes or create a pull request?

**Comment by mellguth2** [comment]
I think, the logical operation between 
(1) testing if procServ is already present and 
(2) prompting the user whether they want to overwrite it
must be an `||` instead of an `&&`. The `&&` short-circuits on the first false condition which is the file existence check, and you rather want it to continue with step (2) if the file is not present.
`#get, build and install procServ
[ -f /usr/bin/procServ ] || read -p "procServ is already installed in /usr/bin. \
Do you want to remove it and install a new one? Type 'yes' if you do. " answer
[ ! "$answer" = "yes" ] && die "Done."
`

**Comment by mellguth2** [comment]
I think the test for the procServ and the subsequent user prompt are easier to maintain when nested:

```
#get, build and install procServ
if [ -f /usr/bin/procServ ]; then
  read -p "procServ is already installed in /usr/bin. \
  Do you want to remove it and install a new one? Type 'yes' if you do. " answer

  [ ! "$answer" = "yes" ] && die "Done."
fi
```

**Comment by huyong1979** [comment]
@mellguth2 Yes, you are right. Your solution of 'nested' has fixed the issue. I updated it.
@leblancOUAL Now it looks for 'procServ' in all possible paths.
